@startuml UMLBridge
package colores {
    Interface Color {
        + colorear()
    }

    class Rojo implements Color {
        + colorear()
    }

    class Azul implements Color {
        + colorear()
    }

    class Amarillo implements Color {
        + colorear()
    }
}
package formas {
    Interface Forma {
        + dibujar()
        + colorear(Color color)
    }

    class Circulo implements Forma {
        + dibujar()
        + colorear(Color color)
    }

    class Cuadrado implements Forma {
        + dibujar()
        + colorear(Color color)
    }

    class Triangulo implements Forma {
        + dibujar()
        + colorear(Color color)
    }
}

Forma --o Color

skinparam linetype ortho
@enduml